//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DerstenVazgecmeIslemleri.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DerstenVazgecmeIslemleriResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DerstenVazgecmeIslemleriResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DerstenVazgecmeIslemleri.Resources.Lang.DerstenVazgecmeIslemleriResources", typeof(DerstenVazgecmeIslemleriResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademik takvim Aktivitesi getirilirken bir hata oluştu.
        /// </summary>
        internal static string AkademikTakvimAktivitesi {
            get {
                return ResourceManager.GetString("AkademikTakvimAktivitesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademik takvim getirilirken bir hata oluştu.
        /// </summary>
        internal static string AkademikTakvimHata {
            get {
                return ResourceManager.GetString("AkademikTakvimHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akademik takvim aktivite güncellenirken bir hata oluştu.
        /// </summary>
        internal static string AkGuncelleme {
            get {
                return ResourceManager.GetString("AkGuncelleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivite kodları getirilirken bir hata oluştu.
        /// </summary>
        internal static string AktiviteHatasi {
            get {
                return ResourceManager.GetString("AktiviteHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ales puan bilinmeyen bir hata meydana geldi!.
        /// </summary>
        internal static string AlesPuanHata {
            get {
                return ResourceManager.GetString("AlesPuanHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az bir tane &quot;ALES Puan Türü&quot; seçiniz.
        /// </summary>
        internal static string AlesPuanTuruSeciniz {
            get {
                return ResourceManager.GetString("AlesPuanTuruSeciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jüride tek bir başkan olabilir.
        /// </summary>
        internal static string baskanvar {
            get {
                return ResourceManager.GetString("baskanvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belge durumları getirilirken bir hata oluştu.
        /// </summary>
        internal static string BelgeHatasi {
            get {
                return ResourceManager.GetString("BelgeHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme kriterleri getirilirken bilinmeyen bir hata meydana geldi!.
        /// </summary>
        internal static string DegerlendirmeHatasi {
            get {
                return ResourceManager.GetString("DegerlendirmeHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dönem getirilirken bir hata oluştu.
        /// </summary>
        internal static string DonemGetirmeHatasi {
            get {
                return ResourceManager.GetString("DonemGetirmeHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekran doldurulurken bilinmeyen bir hata oluştu..
        /// </summary>
        internal static string EkranDoldurma {
            get {
                return ResourceManager.GetString("EkranDoldurma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekran doldurulurken bilinmeyen bir hata oluştu..
        /// </summary>
        internal static string EkranHatasi {
            get {
                return ResourceManager.GetString("EkranHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekran temizlenirken bilinmeyen bir hata meydana geldi!.
        /// </summary>
        internal static string EkranTemizleHata {
            get {
                return ResourceManager.GetString("EkranTemizleHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enstitü Başvuru İşlemleri.
        /// </summary>
        internal static string EnsBasvuruIslem {
            get {
                return ResourceManager.GetString("EnsBasvuruIslem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretim üyesi eklendi..
        /// </summary>
        internal static string hocaeklendi {
            get {
                return ResourceManager.GetString("hocaeklendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öğretim üyesi eklenemedi. .
        /// </summary>
        internal static string hocaeklenemedi {
            get {
                return ResourceManager.GetString("hocaeklenemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen öğretim üyesi daha önceden eklenmiş..
        /// </summary>
        internal static string hocaeklenmis {
            get {
                return ResourceManager.GetString("hocaeklenmis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jüriye eklenecek öğretim üyesini seçiniz..
        /// </summary>
        internal static string hocasec {
            get {
                return ResourceManager.GetString("hocasec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jüriye eklenecek öğretim üyesinin durumunu seçiniz..
        /// </summary>
        internal static string juri_durum_secilmemis {
            get {
                return ResourceManager.GetString("juri_durum_secilmemis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jüri getirilirken bilinmeyen bir hata meydana geldi!.
        /// </summary>
        internal static string JuriHata {
            get {
                return ResourceManager.GetString("JuriHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jüri üyeleri getirilirken bir hata oluştu.
        /// </summary>
        internal static string JuriHatasi {
            get {
                return ResourceManager.GetString("JuriHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işleminde hata oluştu..
        /// </summary>
        internal static string kayithatali {
            get {
                return ResourceManager.GetString("kayithatali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydetme işlemi başarıyla sonuçlandı..
        /// </summary>
        internal static string kayittamam {
            get {
                return ResourceManager.GetString("kayittamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kod tanımları getirilirken bir hata oluştu.
        /// </summary>
        internal static string KodTuruHata {
            get {
                return ResourceManager.GetString("KodTuruHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme kriterleri güncellenirken/kaydedilirken bilinmeyen bir hata meydana geldi..
        /// </summary>
        internal static string KriterGuncelleme {
            get {
                return ResourceManager.GetString("KriterGuncelleme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme kriterlerinde bir hata oluştu.
        /// </summary>
        internal static string KriterHatasi {
            get {
                return ResourceManager.GetString("KriterHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başvuru programları getirilirken bir hata oluştu.
        /// </summary>
        internal static string ProgramGetirilirkenHata {
            get {
                return ResourceManager.GetString("ProgramGetirilirkenHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program türleri getirilirken bir hata oluştu.
        /// </summary>
        internal static string ProgramTurHatasi {
            get {
                return ResourceManager.GetString("ProgramTurHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to puan türleri getirilirken bir hata oluştu.
        /// </summary>
        internal static string PuanTuruHata {
            get {
                return ResourceManager.GetString("PuanTuruHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kaydederken bir hata oluştu.
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinav baraj puanları getirilirken bir hata oluştu.
        /// </summary>
        internal static string SinavBarajPuan {
            get {
                return ResourceManager.GetString("SinavBarajPuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değerlendirme kriterleri için toplam oran 100 olmalıdır..
        /// </summary>
        internal static string toplamoran {
            get {
                return ResourceManager.GetString("toplamoran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yatay Geçiş Öğrenci Başvurusu için Kriterleri Belirle.
        /// </summary>
        internal static string YatayGecisHata {
            get {
                return ResourceManager.GetString("YatayGecisHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl ve Dönem seçmelisiniz.
        /// </summary>
        internal static string yildonemsecilmedi {
            get {
                return ResourceManager.GetString("yildonemsecilmedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yabancı Uyruklu Öğrenci Başvurusu için Kriterleri Belirle.
        /// </summary>
        internal static string YUBasvuruHatasi {
            get {
                return ResourceManager.GetString("YUBasvuruHatasi", resourceCulture);
            }
        }
    }
}
